### ISSUE TITLE
Does not build with old version of boost

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/trRouting#111]
Recent changes added call to optional.has_value, which was only added in boost 1.68. Debian buster have boost 1.67. This function was added to add a compatibility with std::optional (https://www.boost.org/doc/libs/1_74_0/libs/optional/doc/html/boost_optional/relnotes.html)

**Comment by greenscientist** [comment]
Multiple options here: 
* Bump minimal boost version to be 1.68. At this point, buster is oldstable, so people should already upgrade to it. 
* Add a wrapper to this call and chose method appropriate depending if we have an old version of boost or not. Could also eventuellement make it possible to also choose std:optional.

**Comment by tahini** [comment]
Which c++ version are we using? If c++17, we can just switch to std::optional. The optional value is used only internally to avoid using pointers. But there should be a less intrusive way of doing this without requiring changing requirements. But if boost 1.68+ is the new standard, we might as well upgrade.

**Comment by greenscientist** [comment]
Debian stable has 1.74, which is good. But RedHat/Centos 8 seems to still be on 1.66. 

C++17 optional seems to be available since GCC 5, and both those stable distro use GCC 8. 
So I think we can change the minimum requirement

**Comment by tahini** [comment]
Do you know of any potential impact to change minimum requirement to c++17?

**Comment by tahini** [comment]
Or we just try and test and wait and see?

**Comment by greenscientist** [comment]
There should be no changes, just allow us to use new features. Diff up in a few seconds
