### ISSUE TITLE
Compile Capnp files locally

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#13]
The version of libcapnp may vary on the various machines and sometimes for distro, upgrading or downgrading a package to a version that is not in the official repo may have non-negligible side effects on other package version, etc.

The preferable way would be for the build commands to take care of compiling the capnp files with any compatible version available locally.

**Comment by tahini** [comment]
See the file https://github.com/kaligrafy/trRouting/blob/v2c/include/capnp/_generating_classes.txt for how to compile capnp files

**Comment by greenscientist** [comment]
This  can probably be closed now
