### ISSUE TITLE
benchmarks didn't survive housekeeping

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#133]
Benchmarks don't compile anymore. We should find a way to compile the benchmarks all the time when running `make check` without necessarily running them.

**Comment by greenscientist** [comment]
oups, I thought about checking the tests but not the benchmark. 

We should at least have a test on github that enable and build this variant.

**Comment by tahini** [comment]
@greenscientist  it's not just you it's me too! 

The easiest is probably to add an argument to the test executable to really run the benchmark. `make check` will compile and run pretty much nothing (it's > 30 minutes to run the benchmark, no need to waste those precious CPU resources for it at each build.)
