### ISSUE TITLE
Wrong cache path in CSA benchmarks

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#148]
Running: `autoreconf -i && ./configure --enable-benchmark && make check`
Get this segmentation fault:
`../../test-driver: line 109: 69499 Segmentation fault: 11  "$@" > $log_file 2>&1`

**Comment by tahini** [comment]
1- You did run make before make check, right?
2- Did you get the cache for the benchmarks and put it in the right directory, as per instructions in https://github.com/chairemobilite/trRouting/tree/v2c/tests/benchmark_csa You should have, in the csa_benchmark directory, a directory named cache, which contains a directory named demo_transition, which contains the data downloaded.
3- Do you see any files named benchmarkResults_<date>.csv in the directory? If so, is there any output in it?
4- Did you run this on latest v2c, _before_ your last PR with the change in the cache path (which could have broken the benchmarks)

**Comment by tahini** [comment]
Now that #145 is merged, this is an actual bug on macos and ubuntu! :p
