### ISSUE TITLE
formalize the default cache directories

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#149]
Should the default cache directory include the project shortname or not? json2capnp, for now, assumes that custom paths starts inside the cache/PROJECT_SHORTNAME/ directory

**Comment by tahini** [comment]
The trRouting application should not have any notion of "project". We should just send the absolute or relative cache path. Probably same thing for json2capnp. Transition can then manage its caches the way it wants without impacting any other app.
