### ISSUE TITLE
assertion fails: Some time calculation fails

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#151]
error: Assertion failed: (startEpoch && actualEpoch && startEpoch >= 0 && actualEpoch >= 0 && actualEpoch >= startEpoch), function getDurationMicrosecondsNoStop, file calculation_time.cpp, line 35.

No idea when or why though... It seems completely random.

**Comment by greenscientist** [comment]
The way we initialized the time calculation is a little bit more robust now. I'll close this as I doubt we can reproduce the same situation. Reopen if we see the issue again.
