### ISSUE TITLE
Add an API call to get all lines that can be taken between origin and destination

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#177]
For ARTM 2022: add an API call to get all alternatives and return array of all possible lines (uuid, shortname, longname, agency uuid, agency acronym and agency name)

Will be called from evolution, to validate bus, subway and train lines declared by respondents.

**Comment by tahini** [comment]
This API call would receive parameters similar to the route endpoint, but instead of returning the complete detailed alternatives list for the trip, it will return only an array of line objects.

@kaligrafy Does it need additional data? Like the number of alternatives in which this line appears? The total number of alternatives found?

**Comment by kaligrafy** [comment]
If it is easy, it would be great to get the number of alternatives matches and the total number of alternatives, but not essential for evolution right now.

**Comment by greenscientist** [comment]
Please provide a complete documentation for the API first.

**Comment by tahini** [comment]
of course ;-) It should be documented in the APIv2.yml file.

**Comment by greenscientist** [comment]
Also, don't implement right away please, code is too much in flux at the moment.

**Comment by tahini** [comment]
I was thinking of naively using the alternatives calculation and squash the response from it, so it won't interfere with anything you're doing, unless you mean something else by "in flux"?

**Comment by greenscientist** [comment]
Current diffstat: 
	modifié :         connection_scan_algorithm/include/calculator.hpp
	modifié :         connection_scan_algorithm/src/Makefile.am
	modifié :         connection_scan_algorithm/src/calculator.cpp
	modifié :         connection_scan_algorithm/src/forward_calculation.cpp
	modifié :         connection_scan_algorithm/src/forward_journey.cpp
	modifié :         connection_scan_algorithm/src/initializations.cpp
	modifié :         connection_scan_algorithm/src/od_trips_routing.cpp
	modifié :         connection_scan_algorithm/src/optimize_journey.cpp
	modifié :         connection_scan_algorithm/src/parameters.cpp
	modifié :         connection_scan_algorithm/src/preparations.cpp
	modifié :         connection_scan_algorithm/src/resets.cpp
	modifié :         connection_scan_algorithm/src/reverse_calculation.cpp
	modifié :         connection_scan_algorithm/src/reverse_journey.cpp
	modifié :         connection_scan_algorithm/src/transit_routing_http_server.cpp
	modifié :         googletest (contenu non suivi)
	modifié :         include/cache_fetcher.hpp
	modifié :         include/data_fetcher.hpp
	modifié :         include/dummy_data_fetcher.hpp
	modifié :         include/node.hpp
	modifié :         include/od_trip.hpp
	modifié :         include/osrm_fetcher.hpp
	modifié :         include/parameters.hpp
	modifié :         include/path.hpp
	modifié :         include/scenario.hpp
	modifié :         src/nodes_cache_fetcher.cpp
	modifié :         src/od_trips_cache_fetcher.cpp
	modifié :         src/osrm_fetcher.cpp
	modifié :         src/paths_cache_fetcher.cpp
	modifié :         src/scenarios_cache_fetcher.cpp
	modifié :         src/trips_and_connections_cache_fetcher.cpp

**Comment by tahini** [comment]
No foreseeable conflict! :D But yeah, API will be reviewed first...
