### ISSUE TITLE
Auto-update to dockerhub when updating v2c branch

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#18]
trRouting requires osrm_backend, which needs to be compiled by the user, since most distros do not publish packages, with all required dependencies.

If trRouting is published as a docker container, it will avoid this requirement and make users' life easier.

**Comment by greenscientist** [comment]
Tried building a dockerfile for trRouting. Current issue is that the osrm image do not contains the libosrm files. (not sure why). So we cannot base our image on it for the moment.

**Comment by kaligrafy** [comment]
I will need to create a fork of osrm anyway to add support for traffic lights with directions (forward/backward) and stop signs penalties, so we will need to create our own osrm docker files.

**Comment by greenscientist** [comment]
What's the plan to upstream those other features?

**Comment by greenscientist** [comment]
Test build available  at https://hub.docker.com/repository/docker/greenscientist/trrouting

**Comment by tahini** [comment]
@greenscientist  Can we close this issue? Or do we keep it to do automatic updates? I see the dockerhub image is 5 months old...

**Comment by greenscientist** [comment]
I guess we can keep it to automate the build. 
I can look into it, or if you want to explore how this work, I can let you do it.

**Comment by tahini** [comment]
It's basically like for Transition, using a post-commit hook of some kind on branch v2c? I can look into it, just point me in the right direction. It would go in the dockerhub chairemobilite's account I guess? And github can build it?

**Comment by greenscientist** [comment]
Yeah, you just configure the docker account to auto build a specific branch on the github repo. There's a tab for it. Maybe we need to create a target for trRouting in the chairemobilite account, I did not check yet.
