### ISSUE TITLE
add a parameter for caching connections for all scenarios at launch

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#252]
Needed for evolution validation for which we have week/saturday and sunday calls only, so we can cache them all three at launch.

**Comment by greenscientist** [comment]
@kaligrafy What do you means by caching?

**Comment by kaligrafy** [comment]
Instead of caching the connections for the previous request scenario only, add a parameter to allow trRouting to cache for all scenarios at launch. In the OD surveys, the survey trips date can be a weekday, a saturday or a sunday, and we need to accelerate the queries because right now it is unusable for transit trips longer than a few kilometers. So we need to cache the three scenarios at launch: weekday, saturday and sunday services.

**Comment by greenscientist** [comment]
It would be hard to generate all connections on startup, since we currently only do this computation on a first request. 
One alternative could be to specify an higher number of connections array to cache. 
For you use case, you could set it to 3, and have all your data stored.

**Comment by greenscientist** [comment]
We would need to do some benchmark to assess if this really improve the situation.

**Comment by greenscientist** [comment]
Instead of a number of specified as a parameter, we could have an "all" flag, which would store all scenario found.

**Comment by tahini** [comment]
The first connection can take as much as twice the time of the others, so yes, if all connections are others case instead of first case, it will improve. The parameter could be to cache all scenarios? In our case, there is no connection overlap between scenarios, so it won't take too much extra memory.
