### ISSUE TITLE
Allow to specify to use bird distance if osrm not present

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#254]
Currently, when running from the command line, a running osrm instance is required. There's a config option to use bird distance, used in tests, but which can't be set from the command line.

**Comment by greenscientist** [comment]
@tahini @kaligrafy Should we call this option Euclidean distance instead? Or Geodesic ? Orthodromic ? Bird distance seems to be a "frenchism".

**Comment by kaligrafy** [comment]
euclidean

**Comment by kaligrafy** [comment]
en anglais ils disent as the crow flies, mais bird distance c'est connu aussi
