### ISSUE TITLE
Find a unit test framework

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/trRouting#28]
So  many options for C++
https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C++

**Comment by greenscientist** [comment]
We were using GoogleTest in some project at FB. https://github.com/google/googletest
Seems a decent option. Should I investigate more or should I try it?

**Comment by kaligrafy** [comment]
I guess at this point we need to decide if it would not be even faster to just recode trRouting in Rust and test along the way. All the complexity and most of the hard work is already done (algorithm, parameters, etc.) and easily portable to another language.

**Comment by tahini** [comment]
No matter if we rewrite trRouting or not, we need to define a solid test suite, with test cases that cover as much as possible of the code. Rust may reduce the amount of programming errors we make, but it's not magic.

And if we plan to rewrite trRouting in another language, I'd argue it's even more important to have a good test coverage BEFORE!! Even if the algorithms are already there, we will make programming mistakes porting it and no test means hours looking for those mistakes, test will pinpoint where that is!

TDD for the win.

@greenscientist about googleTest, I trust your judgement on this. If it's not too overkill, then you may go ahead and try it?

**Comment by greenscientist** [comment]
> I guess at this point we need to decide if it would not be even faster to just recode trRouting in Rust and test along the way. All the complexity and most of the hard work is already done (algorithm, parameters, etc.) and easily portable to another language.

If we want to discuss this, we should track it in a separate issue and probably have a live meeting on it.

**Comment by kaligrafy** [comment]
Yes, I support TDD.

**Comment by greenscientist** [comment]
PR #35 and #37 are working on this.

**Comment by tahini** [comment]
Closed with #41
