### ISSUE TITLE
We need to initialize startEpoch and endEpoch

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#284]
Otherwise, we may get random crashes:

Assertion failed: (startEpoch && actualEpoch && startEpoch >= 0 && actualEpoch >= 0 && actualEpoch >= startEpoch), function getDurationMicrosecondsNoStop, file calculation_time.cpp, line 35.

**Comment by greenscientist** [comment]
The CalculationTime class does not have a constructor, so we will need to add it.
