### ISSUE TITLE
trRouting does not compile on Linux

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#57]
Since commit 10af9dfd8d8a9ee4d750b9594000a970f2394479, compilation fails with errors like

```
/usr/bin/ld: ../connection_scan_algorithm/src/libcsa.a(program_options.o): in function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/include/boost/program_options/detail/parsers.hpp:32: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
```

**Comment by greenscientist** [comment]
Probably missing a dependency definition that was coming from the OSRM CFLAGS/LIBS

**Comment by tahini** [comment]
The difference between what works and what does not is in the LDFLAGS and they are `-L/usr/local/lib -losrm -fuse-ld=gold -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common`. Adding this to the current LDFLAGS  in `src/Makefile` makes the compilation work. So the missing flag is somewhere in there. I'm not sure I'll have time to look into it before vacation though.

**Comment by greenscientist** [comment]
@which commit work and which one does not? Also can you confirm which platform you are using and which g++ ?

**Comment by greenscientist** [comment]
It's the -fuse-ld=gold

**Comment by greenscientist** [comment]
I can link a simple program using boost_program_option without the gold flags, so the issue is probably something else and adding -use-ld=gold is just hidding it.

**Comment by greenscientist** [comment]
Currently looking into how the libcsa.a is built.
