### ISSUE TITLE
Does not compile on mac M1 CPUs (arm64)

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#63]

**Comment by kaligrafy** [comment]
it stops on boost/program_options on libcsa.a after compiling all the required files.

**Comment by kaligrafy** [comment]
Not sure it is related to boost/program_options though

**Comment by kaligrafy** [comment]
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++14  -g -O2  -L/lib64         -lncurses -L/opt/homebrew/Cellar/capnp/0.8.0/lib -lcapnp -pthread -lkj -pthread -o trRouting agencies_cache_fetcher.o cache_fetcher.o calculation_time.o csv_fetcher.o data_sources_cache_fetcher.o gtfs_fetcher.o households_cache_fetcher.o lines_cache_fetcher.o modes_initialization.o networks_cache_fetcher.o nodes_cache_fetcher.o od_trips_cache_fetcher.o osrm_fetcher.o paths_cache_fetcher.o persons_cache_fetcher.o places_cache_fetcher.o scenarios_cache_fetcher.o services_cache_fetcher.o stations_cache_fetcher.o stops_cache_fetcher.o trips_and_connections_cache_fetcher.o ../connection_scan_algorithm/src/libcsa.a 
libtool: link: g++ -std=c++14 -g -O2 -pthread -pthread -o trRouting agencies_cache_fetcher.o cache_fetcher.o calculation_time.o csv_fetcher.o data_sources_cache_fetcher.o gtfs_fetcher.o households_cache_fetcher.o lines_cache_fetcher.o modes_initialization.o networks_cache_fetcher.o nodes_cache_fetcher.o od_trips_cache_fetcher.o osrm_fetcher.o paths_cache_fetcher.o persons_cache_fetcher.o places_cache_fetcher.o scenarios_cache_fetcher.o services_cache_fetcher.o stations_cache_fetcher.o stops_cache_fetcher.o trips_and_connections_cache_fetcher.o -Wl,-bind_at_load  -L/lib64 -lncurses -L/opt/homebrew/Cellar/capnp/0.8.0/lib -lcapnp -lkj ../connection_scan_algorithm/src/libcsa.a -pthread
ld: warning: directory not found for option '-L/lib64'
Undefined symbols for architecture arm64:
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:

**Comment by greenscientist** [comment]
Can you attach the config.log file ?

**Comment by kaligrafy** [comment]
[config.log](https://github.com/kaligrafy/trRouting/files/6819096/config.log)

**Comment by greenscientist** [comment]
From the log file, it seems it was not able to detect the boost libraries. Are they installed?

**Comment by kaligrafy** [comment]
Let me recreate the log file from scratch, because I think I fixed that problem

**Comment by kaligrafy** [comment]
I updated the config.log file above

**Comment by greenscientist** [comment]
configure:17675: g++ -std=c++14 -c -g -O2  -I/include/boost-0 conftest.cpp >&5
conftest.cpp:25:10: fatal error: 'boost/version.hpp' file not found
#include <boost/version.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by greenscientist** [comment]
Seems like it cannot find the header files

**Comment by greenscientist** [comment]
@kaligrafy Are you able to compile things manually, i.e. using something like the old Makefile ?

**Comment by greenscientist** [comment]
Maybe the instructions here could be useful? https://docs.brew.sh/How-to-Build-Software-Outside-Homebrew-with-Homebrew-keg-only-Dependencies

**Comment by kaligrafy** [comment]
The readme has been updated with the command line to use on ARM mac to successfully compile using hombrew libraries and include.
