### ISSUE TITLE
Replace the "wrong or malformed query" by something more relevant

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#82]
This message happens sometimes when data integrity is not right. But there's a reason why this state happens, the server should return something that helps the caller understand the error instead of this generic message. It doesn't have to be user facing, but at least somethign that can be logged on the server side

**Comment by greenscientist** [comment]
We don't have this message anymore. If was only in V1, should we close this ? @tahini

**Comment by tahini** [comment]
yes, it's fine now, we have other error messages and a way to have even more fine-tuned messages
