### ISSUE TITLE
Add a reason why no routing is found

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#83]
We can augment the NO_ROUTING_FOUND response by something that can be meaningful to the caller, for instance: 

- NO_NODE if there is no stop around the origin and/or destination
- NO_PATH, if there are nodes, but no paths passing by those nodes
- NO_PATH_AT_TIMES, if there are nodes and paths, but not at the specified hours
- NO_ROUTE if there is no route matching the criteria

All those messages could have a AT_ORIGIN or AT_DESTINATION suffix if we know which ends if implied.

If some of these checks are not easy to make and require calculation, we could make them optional with a parameter to the query.

**Comment by kaligrafy** [comment]
Add:
• TOO_LATE if max travel time was reached

**Comment by tahini** [comment]
PR #127 handles the NO_NODE near origin and/or destination reasons
PR #135 handles the NO_SERVICE at origin for forward calculation or destination with reverse calculation.

If there is no specific reasons, it means that no result was found within the queried parameters.

I think getting more details than that may not be the responsibility of the trRouting algorithms. The consumers can play with parameters to get more details if they are interested, like changing departure for arrival time and vice versa to see if there is service at the other end. Or increasing total time or waiting time to see if some results become available.

imho, with #127 and #135, this issue is covered. @kaligrafy what do you think? Can/should trRouting do more?

**Comment by kaligrafy** [comment]
For now, this is good. Finding other cases will be more complicated, but mostly more difficult to explain to the end-user too.

**Comment by tahini** [comment]
Ok so let's close this. If we think we need more eventually, we can open a detailed issue of what to do.
