### ISSUE TITLE
Logging: Add some real logging with timestamps

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#91]
The code contains a few `std::cout << some string`, which is outputted to a file. Those cout should be replace by some logging statements, with timestamps for each statement and level of output.

We have to decide if the debug level need to be specified at compile time, when running an instance of the application, or for each query.

@greenscientist  Any suggestion for a C++ application logging?

**Comment by greenscientist** [comment]
I would need to do a quick review to see what are the good logging libs in 2021 for C++

**Comment by tahini** [comment]
The requests themselves could be picked up by honeycomb, with some opentelemetry data

**Comment by greenscientist** [comment]
modern concept usually ask for structured logging. We could also link directly with open opentelemetry libraries.

**Comment by greenscientist** [comment]
Quick review could point to https://github.com/gabime/spdlog (top project on github)
There's a small attempt to make it structure: https://github.com/takeshibaconsuzuki/structlog

The next one in number of github star is https://github.com/amrayn/easyloggingpp
A log4j implementation for C++: https://github.com/log4cplus/log4cplus

OpenTelemetry implementation is still ongoing, but it's mentionned that it will attempt to use existing library. (https://opentelemetry.io/docs/reference/specification/logs/overview/)

So I think that going with spdlog might be a safe bet at the moment.
