### ISSUE TITLE
CSA: Split the calculator's fields into classes according to their responsibility 

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#95]
The fields of the Calculator class (in `calculator.hpp`) are very numerous, some private, some public, and can be split into classes according to their responsibility:

- [x] Data fields: the agencies, network, services, etc. Singleton for the whole server (if everything is memory) or not (if there's too much data to fit in memory, but we're not there)
- [ ] Calculation fields: node tentative times, trips data, etc. One per alternative calculation, mutable.
- [x] Parameter fields: departure time, access/egress times, etc. One per query, immutable for the whole query

**Comment by tahini** [comment]
parameter fields were completed with PR #113

**Comment by greenscientist** [comment]
Pytting some benchmark data, before I break too much stuff: 
,Forward - no alternatives,Arrival time - no alternatives,Forward - alternatives,Arrival time - alternatives
Short Central Trip (Promenade Masson to Villeray),0.003599,0.004321702,0.330096881,0.438279105
Short Central Trip - outside time range,0.002556168,0.000904083,0.002495002,0.000891709
Long Central Trip (Ahuntsic to Sud-Ouest),0.005211185,0.005928372,1.199193520,1.037634727
Periphery of the transit network (Eastern bout de l'île),0.002771044,0.003067303,0.299603383,0.121376275
Crossing more than half the transit network territory - morning (From PAT to Lasalle),0.012421168,0.011700344,2.647886211,2.400217303
Crossing more than half the transit network territory - noon (From PAT to Lasalle)),0.009350837,0.011089714,2.218660212,3.054860049
Crossing more than half the transit network territory - evening (From PAT to Lasalle),0.009568819,0.013452106,1.964647100,3.200463157
Crossing more than half the transit network territory - night (From PAT to Lasalle),0.005003799,0.007940269,0.206043803,1.366890728
Crossing more than half the transit network territory - outside time range (From PAT to Lasalle),0.000890670,0.000965988,0.001033700,0.000884046
West to east of the transit network (Baie d'urfe to RDP),0.015407004,0.019430594,3.068646565,4.404804738
Central Trip - no alternative (Polytechnique to Villeray),0.003196142,0.003029138,0.005303438,0.005456308
Short Downtown trip,0.002364512,0.002177517,0.013996285,0.013180132

**Comment by greenscientist** [comment]
first of a series to remove the Vector indexes: #166

**Comment by greenscientist** [comment]
Data fields moved to a TransitData object in #196

**Comment by greenscientist** [comment]
There's still some data being used from the global Parameter objects that still need cleanup
